version: '3'

volumes:
  es_data:
    driver: local 
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.49.1
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/promtheus
    restart: always
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - monitor-net

  node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: node-exporter
    ports:
      - '9100:9100'
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:10.3.1
    container_name: grafana
    volumes: 
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_SERVER_ROOT_URL=http://grafana.server.name
    ports:
      - 3000:3000
    networks:
      - monitor-net
      - elastic
    depends_on:
      - prometheus
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    cap_add:
      - IPC_LOCK
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=secret
    networks:
      - elastic
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
  loki:
    image: grafana/loki:main
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:main
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - loki
networks:
  monitor-net:
    driver: bridge
  elastic:
    driver: bridge
  loki:
    driver: bridge
