version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD: secret
      - GF_SERVER_ROOT_URL: http://grafana.server.name
    ports:
      - 3000:3000
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    restart: always
    networks:
      - monitor-net


networks:
  monitor-net:
    driver: bridge